- op: add
  path: /stages/0/tests/-
  value:
    image: docker.io/andreasgerstmayr/scorecard-test-kuttl:1678812029
    entrypoint:
    - entrypoint
    - --namespace-per-test
    - --troubleshooting-script
    - |
      namespace=`kubectl get -A pod -l app.kubernetes.io/name=opentelemetry-operator,control-plane=controller-manager -o jsonpath='{.items[0].metadata.namespace}'`
      pod=`kubectl get -A pod -l app.kubernetes.io/name=opentelemetry-operator,control-plane=controller-manager -o jsonpath='{.items[0].metadata.name}'`

      kubectl logs deployment/opentelemetry-operator-controller-manager manager --namespace $namespace
      date
      kubectl get event --namespace $namespace -o custom-columns=FirstSeen:.firstTimestamp,LastSeen:.lastTimestamp,Count:.count,From:.source.component,Object:.involvedObject.name,Type:.type,Reason:.reason,Message:.message

      kubectl describe -A pod -l app.kubernetes.io/name=opentelemetry-operator,control-plane=controller-manager
      kubectl describe -A deployment -l app.kubernetes.io/name=opentelemetry-operator,control-plane=controller-manager
      kubectl get -A pod
      date
    labels:
      suite: kuttlsuite
      test: kuttltest1
