- op: add
  path: /stages/0/tests/-
  value:
    image: docker.io/andreasgerstmayr/scorecard-test-kuttl:1677079022
    entrypoint:
    - entrypoint
    - --namespace-per-test
    labels:
      suite: kuttlsuite
      test: kuttltest1
