name: "Scorecard tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scorecard-tests:
    name: test on k8s
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        kube-version:
          - "1.19"
          - "1.25"

    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: "install kuttl"
        run: ./hack/install-kuttl.sh

      - name: "prepare cluster"
        env:
          KUBE_VERSION: ${{ matrix.kube-version }}
        run: make prepare-e2e KUBE_VERSION=$KUBE_VERSION VERSION=e2e

      - name: "run scorecard tests"
        run: make scorecard-tests
